### ISSUE TITLE
ImportError: cannot import name 'ws_received_send_signal_task

### ISSUE THREAD

**Issue by manojLondhe** [HealthByRo/universal_notifications#43]
Hi,

Getting error  `ImportError: cannot import name 'ws_received_send_signal_task` when importing anything from this package.

Any suggestions, to fix this are appreciated, Thanking in advance.

----------------------------------------

**Here are steps I took**
1. Created virtual env., activated it
```
$ cd ~/Python_environments
$ python -m venv universal-notifications-test
$ source ~/Python_environments/universal-notifications-test/bin/activate
```
2. Created Django project
```
(universal-notifications-test)$ cd ~/Python_projects
(universal-notifications-test)$ pip3 install Django==2.2.7
(universal-notifications-test)$ pip3 install universal_notifications
(universal-notifications-test)$ pip3 install mysqlclient
(universal-notifications-test)$ django-admin startproject universalNotificationsTest
(universal-notifications-test)$ cd universalNotificationsTest
```

3. Edited universalNotificationsTest/settings.py to use mysql DB
```
# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db_name',
        'USER': 'db_user',
        'PASSWORD': 'db_pwd',
        'HOST': '127.0.0.1',
        'PORT': '',
    }
}
```

4. Ran migrations
```
(universal-notifications-test)$ python manage.py migrate
(universal-notifications-test)$ python manage.py runserver
```

5. Stopped server, add new blog app
```
(universal-notifications-test)$ python manage.py startapp blog
```

6. Edited `universalNotificationsTest/settings.py` to add `django.contrib.sites`, `blog`, `universal_notifications` apps

```
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites', # ++
    'blog', # ++
    'universal_notifications' # ++
]
```

7. Edited blog/models.py as

```
from django.db import models

class Blog(models.Model):
    published = models.BooleanField(default=True)
    title     = models.CharField(max_length=50)
    content   = models.TextField(null=True, default='')

    class Meta:
        db_table = "blogs"

    def to_dict(self):
        return {
            'id': self.id,
            'published': self.published,
            'title': self.title,
        }
```

8. Made migrations, and migrated
```
(universal-notifications-test)$ python manage.py makemigrations
(universal-notifications-test)$ python manage.py migrate
```

9. Now when I try to import something from universal_notifications, it shows errors as
9.1 Edited blog/models.py as

```
from django.db import models
from universal_notifications.notifications import EmailNotification

class Blog(models.Model):
    published = models.BooleanField(default=True)
    title     = models.CharField(max_length=50)
    content   = models.TextField(null=True, default='')

    class Meta:
        db_table = "blogs"

    def to_dict(self):
        return {
            'id': self.id,
            'published': self.published,
            'title': self.title,
        }
```

9.2 Error shown as

```
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "~/Python_environments/universal-notifications-test/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "~/Python_environments/universal-notifications-test/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "~/Python_environments/universal-notifications-test/lib/python3.6/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "~/Python_environments/universal-notifications-test/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "~/Python_environments/universal-notifications-test/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "~/Python_environments/universal-notifications-test/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "~/Python_environments/universal-notifications-test/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "~/Python_environments/universal-notifications-test/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "~/Python_projects/universalNotificationsTest/blog/models.py", line 2, in <module>
    from universal_notifications.notifications import EmailNotification
  File "~/Python_environments/universal-notifications-test/lib/python3.6/site-packages/universal_notifications/notifications.py", line 35, in <module>
    from universal_notifications.backends.websockets import publish
  File "~/Python_environments/universal-notifications-test/lib/python3.6/site-packages/universal_notifications/backends/websockets.py", line 6, in <module>
    from universal_notifications.tasks import ws_received_send_signal_task
ImportError: cannot import name 'ws_received_send_signal_task'
```

**Comment by ArnaudPel** [comment]
Not sure it will help, but the install command [on documentation main page](https://pypi.org/project/universal-notifications/) is with a dash
>pip install universal-notifications

instead of what I seem to notice in your issue (underscore)
>pip install universal_notifications
